version: '3.5'

services:
  chatbot:
    build: .
    volumes:
      - .:/app
    environment:
      - TELEGRAM_ACCESS_TOKEN=${TELEGRAM_ACCESS_TOKEN}
      - TELEGRAM_VERIFY=${TELEGRAM_VERIFY}
      - TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}
